### ISSUE TITLE
Use of SECRET_KEY

### ISSUE THREAD

**Issue by milgner** [pinterest/snappass#111]
I just came across this project and am wondering how the `SECRET_KEY` environment variable is used. I did a search for `secret_key` in the repo and could see [it being assigned](https://github.com/pinterest/snappass/blob/5747ee2d14e2c887b38819e1fb89e404baa5747b/snappass/main.py#L23) but no access to that property afterwards.

In my understanding, the keys are generated on the fly for each secret and included in the link, so there shouldn't be a need for a global secret? Except maybe for adding an additional HMAC at the end - but I couldn't come up with a scenario where this would actually help here.
Although I see that you do the decryption on the server and then render the decrypted secret, while you could do HMAC verification, my understand is that an HMAC would only make sense if an attacker can modify the encrypted data.

Incidentally I built a very similar solution a while ago: https://github.com/milgner/keedrop/ :smile: 
There I decided to do all the cryptography in the browser so that the server operator never has a chance to see the encoded data. HMAC verification wouldn't work as the secret is already gone from the server at the time of decryption.

But maybe `app.secret_key` is only a left-over and can be removed?

**Comment by devinlundberg** [comment]
app.secret_key is typically used by Flask under the hood for signing session cookies, but it doesn't look like snappass uses those. I have also seen it used by some flask extensions for generating derived keys for CSRF protection and similar functionality. From a quick skim of the dependencies I don't see an obvious use case there either (itsdangerous is the only non-flask dependency that I know uses it and I believe we are just including it to pin the version since it is also included by Flask itself). I haven't tested running snappass without the secret key, but if the server runs, it should be safe to remove.

**Comment by milgner** [comment]
Thank you for the explanation! :+1: I'm unfamiliar with Flask and had assumed that it has to do with the password encryption scheme :sweat_smile:
