### ISSUE TITLE
Cannot Create a secure connection 

### ISSUE THREAD

**Issue by WCSLoschy** [pinterest/snappass#44]
Running Redis 3.0.6 (00000000/0) 64 bit server along side Snappass. 

I can type in the password which gets stored however I have an issue when trying to access that password either locally or remotely for testing purposes. 

The error is: 
This site can’t provide a secure connection
0.0.0.0 sent an invalid response

Does anyone know a fix?

**Comment by WCSLoschy** [comment]
Edit: I do understand that changing the https to http solves this issue, however, doesn't that remove the "secure" part of it?

**Comment by jobwat** [comment]
Indeed, using http instead of https remove the secure part of the http connexion :)

This project does not provide the SSL encryption layer mechanism required to https.
This project assume you'd be able to add the secure layer to your host yourself.

I personally host my snappass instance on Amazon AWS, and I did add a SSL certificate to the corresponding ELB.

Hope this help!
If you still lost on how to SSLize your snappass instance, please tell more on how you're using it (environment, platform, etc)

**Comment by jameswthorne** [comment]
To ensure an HTTPS connection, you will need to use apache or nginx as a reverse proxy to the SnapPass Python application.

@jobwat also provided another method.

Additionally, I have SnapPass running on Google Cloud App Engine which takes care a lot of this for you. See #49.

**Comment by internetamonymous** [comment]
@jobwat @jameswthorne  I need to setup apache forntend for the snappass and also install SSL, my Operating system : centos 7.x and also how to change the port number from 5000 to 443 after SSLizing.

**Comment by jobwat** [comment]
Dear @internetamonymous, you could have consider searching by yourself first as it's a rather common issue.
Have a look at these responses [here](https://serverfault.com/questions/25423/apache-virtualhost-with-mod-proxy-and-ssl/25518#25518) and [there](https://serverfault.com/questions/84821/apache-proxypass-with-ssl/84828#84828)

Good luck

**Comment by internetamonymous** [comment]
@jobwat Thanks mate, I will try these configs.

**Comment by nichochar** [comment]
Closing since this isn't a snappass issue.
